import { useState } from 'react';
import { useBrand } from '../context/BrandContext';
import { Share2, Download, Plus, Trash2 } from 'lucide-react';

const BillGenerator = () => {
  const { config, user } = useBrand();
  const [items, setItems] = useState([]);
  const [currentName, setCurrentName] = useState("");
  const [currentPrice, setCurrentPrice] = useState("");
  const [customerName, setCustomerName] = useState("");

  const addItem = () => {
    if(!currentName || !currentPrice) return;
    setItems([...items, { name: currentName, price: parseFloat(currentPrice) }]);
    setCurrentName("");
    setCurrentPrice("");
  };

  const total = items.reduce((sum, item) => sum + item.price, 0);

  // 1. SHARE ON WHATSAPP
  const handleShare = () => {
    const itemList = items.map(i => `${i.name}: ₹${i.price}`).join('%0a');
    const text = `*Invoice from ${config.businessName}*%0a----------------%0a${itemList}%0a----------------%0a*Total: ₹${total}*%0a%0aThank you ${customerName}!`;
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  // 2. PRINT / DOWNLOAD
  const handlePrint = () => {
    window.print(); 
  };

  return (
    <div className="pb-20">
                 <div className="print:hidden space-y-4 mb-8">
        <h2 className="text-xl font-bold">New Invoice</h2>
          <div className="bg-white p-4 rounded-xl shadow-sm space-y-3">
          <input 
             placeholder="Customer Name" 
             className="w-full p-2 border rounded"
             value={customerName} onChange={e => setCustomerName(e.target.value)}
          />
          <div className="flex gap-2">
             <input placeholder="Item" className="flex-1 p-2 border rounded" value={currentName} onChange={e => setCurrentName(e.target.value)} />
             <input placeholder="Price" type="number" className="w-20 p-2 border rounded" value={currentPrice} onChange={e => setCurrentPrice(e.target.value)} />
             <button onClick={addItem} style={{backgroundColor: config.themeColor}} className="text-white p-2 rounded"><Plus /></button>
          </div>
        </div>
      </div>

      <div id="invoice" className="bg-white p-8 rounded-xl shadow-lg border border-gray-100 min-h-[400px] flex flex-col">
        
        {/* Header with Logo */}
        <div className="text-center border-b pb-6 mb-6">
           {config.logoUrl && <img src={config.logoUrl} className="w-16 h-16 mx-auto mb-2 object-contain" />}
           <h1 className="text-2xl font-bold text-gray-800">{config.businessName}</h1>
           <p className="text-sm text-gray-500">{user.mobileNumber}</p>
        </div>

        {/* Customer Info */}
        <div className="mb-6">
           <p className="text-xs text-gray-400">Bill To:</p>
           <p className="font-bold text-lg">{customerName || "Walk-in Customer"}</p>
           <p className="text-xs text-gray-400">Date: {new Date().toLocaleDateString()}</p>
        </div>

        {/* Items */}
        <div className="flex-1">
           <table className="w-full text-sm">
             <thead>
               <tr className="border-b text-left text-gray-500"><th className="pb-2">Item</th><th className="pb-2 text-right">Price</th></tr>
             </thead>
             <tbody>
               {items.map((item, i) => (
                 <tr key={i} className="border-b border-dashed">
                   <td className="py-3">{item.name}</td>
                   <td className="py-3 text-right">₹{item.price}</td>
                 </tr>
               ))}
             </tbody>
           </table>
        </div>

        {/* Total */}
        <div className="border-t pt-4 mt-4 flex justify-between items-center">
           <span className="font-bold text-gray-600">Total Amount</span>
           <span className="font-bold text-2xl text-gray-900">₹{total}</span>
        </div>
        
        <p className="text-center text-[10px] text-gray-400 mt-8">Generated by PocketBiz</p>
      </div>

      {/* ACTIONS (Hidden when printing) */}
      <div className="print:hidden fixed bottom-20 left-4 right-4 flex gap-3">
         <button onClick={handlePrint} className="flex-1 bg-gray-900 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2">
            <Download size={18} /> Download
         </button>
         <button onClick={handleShare} className="flex-1 bg-green-600 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2">
            <Share2 size={18} /> WhatsApp
         </button>
      </div>

    </div>
  );
};

export default BillGenerator;